spring.application.name=Alquiler_Vehiculos-2
server.port=8080
spring.datasource.url=jdbc:mysql://localhost/proyecto
spring.datasource.username=root
spring.datasource.password=46646915

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update